### ISSUE TITLE
open/read/write/close issue

### ISSUE THREAD

**Issue by BernardXiong** [plctlab/mlibc#23]
目前的代码整体逻辑不对，或者说，mlibc应该提供的API是什么？沿着这份API，它对应的实现应该是什么。

也就是说，mlibc对外的边界是什么？边界确立清楚了，才清楚它的实现可以是什么样的。例如open

![image](https://github.com/plctlab/mlibc/assets/1241087/cec70649-6ea4-4bfd-bf71-1b169edacf16)

**Comment by 0Bitbiscuits** [comment]
我根据您的描述重新审视了我的代码，我发现malloc部分的代码的确是结构不清晰的，而fdopen部分的实现是在您所描述的这个框架内的，我根据我的理解绘制了fopen和malloc函数的调用图，您看一下这样是否正确。
![fdopen](https://github.com/plctlab/mlibc/assets/102195050/bb4cff3a-098c-4284-aafb-13141a552ebc)
![malloc](https://github.com/plctlab/mlibc/assets/102195050/b35de4ba-a55d-4b37-a3f7-b79c8c31579e)

**Comment by 0Bitbiscuits** [comment]
对于open/read/write/close的函数实现我有一些疑问：
这些函数在rt-thread系统中已经有了对应的定义，而且还是强定义。那么这样我在mlibc中的实现就只能是弱引用，在系统开启posix接口后mlibc的实现就不加入编译了。这样的结果应该是我们的目标结果吗？

**Comment by BernardXiong** [comment]
是的，libc中可以有系列的弱符号定义，当外面开启后，内部的弱符号定义自然就不生效了。这个和C++中的函数被重载有些类似
